.TH _PRINTF 1 "January 2024" "Version 1.0" "_printf Manual"

.SH NAME
_printf \- custom printf implementation

.SH SYNOPSIS
.B _printf
[\fIFORMAT\fR [\fIARGUMENT\fR]...]

.SH DESCRIPTION
The \fB_printf\fR command is a custom implementation of the printf function, providing a flexible and extensible way to format and print output to the standard output stream.

.PP
The command accepts a format string and optional arguments, offering a similar interface to the standard printf function found in the C programming language.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display a help message describing the usage of the \fB_printf\fR command and exit.

.SH EXAMPLES
Display a simple sentence:
.B _printf "Hello, world!\n"

.PP
Display formatted output, specifying an integer:
.B _printf "Length: [%d]\n" 10

.SH SEE ALSO
.BR printf (1),
.BR man (1).

.SH BUGS
The program is still being debugged and slowly being improved. So far no known bugs have been reported for this version of \fB_printf\fR.

.SH AUTHORS
The \fB_printf\fR command was primarily implemented by Joel Mwangala and Brian Ogada Mbeke. Contributions were made by both Droidna405 <joemwangala@gmail.com> and MBEKE <email.address>.

.SH COPYRIGHT
\fB_printf\fR is opensource software: you are free to use it and redistribute it. There is NO WARRANT. It was written mainly for education purposes. 

.SH REPORTING BUGS
Please report any bugs to: https://github.com/Droidna405/printf.git

.SH NOTES
This manpage is designed to follow the conventions of manpages and provides comprehensive information about the custom \fB_printf\fR implementation. Users are encouraged to refer to this documentation for assistance with the command's usage and features.
